name: Build BeyBlade

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
        cache: maven

    - name: Build Maven project
      run: mvn -B clean package

    - name: Create JavaFX app image
      run: |
        jpackage --name BeyBlade --input target --main-jar BeyBlade-1.0-SNAPSHOT.jar --main-class com.windows.Main --type app-image --dest target

    - name: Zip application
      run: powershell Compress-Archive target/BeyBlade target/BeyBlade-windows.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: BeyBlade-windows
        path: target/BeyBlade-windows.zip